# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RSRIIIl2xheSwPR-MaLgeeKO--wCviH8

# **Dashboard**

**Встановлення бібліотек та імпорт модулів**
"""

!pip install plotly ipywidgets pandas   # встановлюємо необхідні пакети для роботи дашборду

from google.colab import output
output.enable_custom_widget_manager()   # дозволяємо використання інтерактивних віджетів у Colab

import pandas as pd      # робота з таблицями
import numpy as np       # робота з масивами, базова математика
import plotly.express as px            # швидкі інтерактивні графіки
import plotly.graph_objects as go      # більш детальні графічні об’єкти

import ipywidgets as widgets           # інтерактивні елементи (випадаючі списки тощо)
from IPython.display import display    # відображення об’єктів у ноутбуці

from google.colab import files         # інструмент для завантаження файлів у Colab

"""**Завантаження CSV-файлу з результатами індексу**"""

print("Завантаж, файл data_index.csv")
uploaded = files.upload()                # користувач завантажує файл вручну у Colab

df = pd.read_csv("data_index.csv")       # читаємо таблицю з інтегральними індексами
df.head()                                # перегляд перших рядків для перевірки структури

"""**Вибір потрібного індексу та фільтрація даних**"""

# Перейменуємо індекс у коротшу назву
if "econ_security_index_step1" in df.columns:
    df["econ_index"] = df["econ_security_index_step1"]
elif "economic_security_index" in df.columns:
    df["econ_index"] = df["economic_security_index"]
else:
    raise ValueError("Не знайшов ні econ_security_index_step1, ні economic_security_index")

# приберемо рядки без індексу або ISO3 коду
df = df.dropna(subset=["econ_index", "iso3c"])

# беремо останній рядок
latest_year = int(df["year"].max())          # автоматично визначаємо найновіший доступний рік
df_latest = df[df["year"] == latest_year].copy()

print("Використовуємо рік:", latest_year)
df_latest.head()

"""**Географічна мапа економічної безпеки**"""

fig_map = px.choropleth(
    df_latest,
    locations="iso3c",           # ISO3-код країни
    color="econ_index",          # значення індексу
    hover_name="country",        # ім’я країни у підказці
    hover_data={"econ_index": ":.3f", "year": True},
    color_continuous_scale="YlGnBu",   # синьо-зелена палітра
    title=f"Economic Security Index, {latest_year}"
)

fig_map.update_layout(
    coloraxis_colorbar_title="Index",
    margin=dict(l=0, r=0, t=40, b=0)
)

fig_map.show()     # показуємо інтерактивну карту

"""**ТОП-10 країн за економічною безпекою**"""

# Top 10
top10 = df_latest.sort_values("econ_index", ascending=False).head(10)

fig_top = px.bar(
    top10,
    x="econ_index",
    y="country",
    orientation="h",
    title="Top 10 країн за рівнем економічної безпеки",
    labels={"econ_index": "Index", "country": ""}
)
fig_top.update_layout(yaxis=dict(autorange="reversed"))  # щоби країни були зверху вниз
fig_top.show()

"""**10 країн з найнижчим рівнем безпеки**"""

# Bottom 10
bottom10 = df_latest.sort_values("econ_index", ascending=True).head(10)

fig_bottom = px.bar(
    bottom10,
    x="econ_index",
    y="country",
    orientation="h",
    title="Bottom 10 країн за рівнем економічної безпеки",
    labels={"econ_index": "Index", "country": ""}
)
fig_bottom.update_layout(yaxis=dict(autorange="reversed"))
fig_bottom.show()

"""**Підготовка індикаторів для профілю країни**"""

stim_cols = ["trade_z", "fdi_z", "income_z", "lending_z"]     # стимулятори
destim_cols = ["unemployment_z", "gov_debt_z"]                 # дестимулятори

# перевернуті дестимулятори
for col in destim_cols:
    rev_col = col + "_rev"
    if rev_col not in df.columns:
        df[rev_col] = -df[col]               # інверсія для порівняння

profile_cols = stim_cols + [c + "_rev" for c in destim_cols]

"""**Графік профілю індикаторів обраної країни**"""

latest_year = int(df["year"].max())
countries_latest = df[df["year"] == latest_year]["country"].sort_values().unique()

country_dropdown = widgets.Dropdown(
    options=countries_latest,
    description="Країна:",
    layout=widgets.Layout(width="50%")
)

def plot_country_profile(country):
    #  рядок для обраної країни - останній рік
    row = df[(df["country"] == country) & (df["year"] == latest_year)]
    if row.empty:
        print("Немає даних для цієї країни")
        return

    row = row.iloc[0]

    # колонки, які реально існують
    cols_existing = [c for c in profile_cols if c in df.columns]
    vals = row[cols_existing]

    df_prof = pd.DataFrame({
        "indicator": cols_existing,
        "value": vals.values
    })

    name_map = {
        "trade_z": "Trade (z)",
        "fdi_z": "FDI (z)",
        "income_z": "Income (z)",
        "lending_z": "Lending (z)",
        "unemployment_z_rev": "Unemployment (rev z)",
        "gov_debt_z_rev": "Gov debt (rev z)"
    }
    df_prof["indicator"] = df_prof["indicator"].map(
        lambda x: name_map.get(x, x)
    )

    fig = px.bar(
        df_prof,
        x="indicator",
        y="value",
        title=f"Профіль індикаторів: {country} ({latest_year})",
        labels={"indicator": "", "value": "Z-score / rev Z"},
    )
    fig.update_layout(xaxis_tickangle=-30)
    fig.show()

widgets.interact(plot_country_profile, country=country_dropdown);

"""**Таблиця країн з найвищим індексом**"""

df_latest[["country", "year", "econ_index"]].sort_values("econ_index", ascending=False).head(20)